comment: false
github_checks:
  annotations: true

coverage:
  precision: 2
  range: '20...60'
  round: down
  status:
    changes: false
    patch:
      default:
        informational: true
    project:
      default:
        target: auto
        threshold: 5%

flags:
  browserslist-to-targets:
    paths:
      - packages/browserslist-to-targets/
  plugin-ajv:
    paths:
      - packages/plugin-ajv/
  plugin-lightningcss:
    paths:
      - packages/plugin-lightningcss/
  plugin-write-assets:
    paths:
      - packages/plugin-write-assets/
  pointe:
    paths:
      - packages/pointe/
  types:
    paths:
      - packages/types/
