ls:
  packages/*/src:
    .ts: kebab-case
    .d.ts: kebab-case
    .spec.ts: kebab-case
  scripts:
    .js: kebab-case
    .mjs: kebab-case
    .cjs: kebab-case

ignore:
  - .eslintrc.json
  - .git
  - .github
  - .vscode
  - coverage
  - lib
  - node_modules
