name: release

on:
  push:
    tags:
      - "v*"
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: install dependencies
        run: pnpm install
      - name: typecheck
        run: pnpm run typecheck
      - name: lint
        run: pnpm run lint
      # - name: test
      #   run: pnpm run test
      - name: build
        run: pnpm run build
      - name: release
        if: github.repository == 'escapace/yeux' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run publish -- ${{ github.ref_name }}
      # - name: code coverage
      #   uses: codecov/codecov-action@v2.1.0
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
